# Eureka Server Port
server.port=8761

spring.application.name=eureka-server

# Do not register with itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Server hostname
eureka.instance.hostname=eureka-server

# Default zone
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always